### ISSUE TITLE
Openapi V2 support (aka swagger)

### ISSUE THREAD

**Issue by tgjonestx** [znsio/specmatic#613]
Is OpenAPI V2 supported by Specmatic? 

I'm not sure if I ran into a bug or a limitation. I looked at the documentation, but could not find clarification on what exactly is supported in terms of versions for the OpenAPI spec.

I tried running `test` with OpenAPI V2 (aka swagger) YAML. The command failed with an error like:
```
Error parsing file bookinfo.yaml
  attribute openapi is missing
Could not parse contract bookinfo.yaml, please validate the syntax using https://editor.swagger.io
Load Error FAILED
Reason: Could not parse contract bookinfo.yaml, please validate the syntax using https://editor.swagger.io



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: Could not parse contract bookinfo.yaml, please validate the syntax using https://editor.swagger.io

Tests run: 1, Successes: 0, Failures: 1, Errors: 0
```

I went to https://editor.swagger.io as suggested, and entered my yaml doc.  The swagger editor confirmed that it is valid.

**Comment by harikrishnan83** [comment]
@tgjonestx Thanks for reaching out to us. Specmatic does not support OpenAPI v2. We only support 3.0.x onwards. Support for 3.1.x is coming soon. Please feel free to raise issues on Github if you have any other questions.
